version: '3'
services:
  ipfs:
    image: ipfs/go-ipfs:latest
    hostname: ipfs_host
    volumes:
    - "./export:/export"
    - "./data/ipfs:/data/ipfs"
    ports:
    - "5001:5001"
    - "4001:4001"
    - "8080:8080"

  app:
    build: .
    image: inui_ipfs:latest
